server:
  port: 8099
spring:
  datasource:
    name: customer_db
    url: jdbc:mysql://localhost:3306/customer_db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: root
    password: 199828
mybatis-plus:
  #信息输出设置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl