server:
  port: 8099
spring:
  datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/customer_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  username: root
  password: 199828
mybatis-plus:
  #信息输出设置
  configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl